apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-index-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/blog"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-index-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
